doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        # driver: pdo_mysql
        # host: localhost
        # dbname: ideasoft
        # port: 3306
        # user: core_multisite_user
        # password: core_multisite1234
        # charset:  UTF8
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App